name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clone Repository
      run: git clone https://github.com/binwiederhier/ntfy-android.git
    - name: Add FCM
      run:
        cp ./google-services.json ./ntfy-android/app/
    - name: Replace URL in XML
      if: ${{ env.BASE_URL != '' }}
      run: |
        sed -i "s#\(<string name=\"app_base_url\" translatable=\"false\">\)https://ntfy.sh\(</string>\)#\1${{ env.BASE_URL }}\2#" ./ntfy-android/app/src/main/res/values/values.xml
        cat ./ntfy-android/app/src/main/res/values/values.xml
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: |
        cd ./ntfy-android
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd ./ntfy-android
        ./gradlew assemblePlayRelease
    - uses: actions/upload-artifact@v4
      with:
        name: nfty-artifact
        path: ./ntfy-android/app/build/outputs/apk/play/release/